[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm ci --prefix frontend_ndi_2025",
  "npm ci --prefix backend_ndi_2025"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend_ndi_2025",
  "npm run build --prefix backend_ndi_2025"
]

[start]
cmd = "npm run start:prod --prefix backend_ndi_2025"
